### ISSUE TITLE
Fill out README Prerequisites

### ISSUE THREAD

**Issue by zahin-mohammad** [mochahub/coinprice-scraper#26]
We need to document the steps needed for someone to be able to run this project for the first time (dependencies, running the docker images for the data services).
Rough steps:
- clone repo
- run the docker-compose to start influxdb and psql
- run psql migrations
- run app

**Comment by javiercaamano** [comment]
can u give me more info? how can I should help you? I'm beginner programmer and this is my first task designated learning Github

**Comment by zahin-mohammad** [comment]
> can u give me more info? how can I should help you? I'm beginner programmer and this is my first task designated learning Github

This task is just doccumenting how to run the application. I haven't filled this out yet as I have not had to reset my development environment in a while, so I am unaware of the full set of steps needed to run the application. If you are a beginner programmer this might be challenging... I'll try to fill this out once I am finished with exams, but no guarantees. If you are new I would learn how to work `golang` projects, the golang docs are good, and there are some good resources on youtube.

**Comment by zahin-mohammad** [comment]
Requires:
- docker, docker-compose
- golang

Steps:
- clone repository
- run `docker-compose up` to download and run influxDB and PSQL
- run `go get -u ./... -v` to install go dependencies
- run `./scripts/generate-database-models.sh`
- run `./scripts/run-psql--database-migrations.sh`
- run `go run scraper/main.go `

@javiercaamano try running through these steps and let me know if u run into any issues (fair warning, I will try and guide/help you when I have time, but you will have to do some debugging on your own to get things working)

**Comment by zahin-mohammad** [comment]
@javiercaamano I updated the readme with setup instructions. If you are still interested in contributing, please take a look at the readme on how to setup your local development environemnt.
